version: "3"

services:
  elite:
    image: demosocket/elite-blog:v1
    container_name: elite
    links:
      - postgresql
      - redis2
    ports:
      - "8080:8080"

  postgresql:
    image: library/postgres:latest
    container_name: postgres2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elite_blog
    volumes:
      - ./psql:/docker-entrypoint-initdb.d
    restart: always
    expose:
      - 5432

  redis2:
    image: library/redis:latest
    container_name: redis2
    restart: always
    expose:
      - 6379
